# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'easyMusic' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for easyMusic
  rn_path = '../node_modules/react-native'
   pod 'React', :path => rn_path, :subspecs => [
      'ART',
      'Core',
      'CxxBridge',
      'DevSupport',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'RCTCameraRoll'
    ]
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    # React Native third party dependencies podspecs
    # pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
    # pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
    # If you are using React Native <0.54, you will get the following error:
    # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
    # Use the following line instead:
    # pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
     pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

    pod 'RNSVG', :path => '../node_modules/react-native-svg'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  # pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'RNAudio', :path => '../node_modules/react-native-audio'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  # pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

